services:
  nginx:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

  php:
    build:
      context: .
      dockerfile: php.dockerfile
    volumes:
      - ./src:/var/www/html
    ports:
      - "9000:9000"

  postgres:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_DB: oleg
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: auazze
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  composer:
    build:
      context: .
      dockerfile: composer.dockerfile
    volumes:
      - ./src:/var/www/html

  node:
    image: node:18-alpine
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
    command: npm run dev -- --host=0.0.0.0
    ports:
      - "5173:5173"

volumes:
  pgdata: