services:
  nginx:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

  php:
    build:
      context: .
      dockerfile: php.dockerfile
    volumes:
      - ./src:/var/www/html

  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: oleg
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: auazze
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  composer:
    build:
      context: .
      dockerfile: composer.dockerfile
    volumes:
      - ./src:/var/www/html

volumes:
  pgdata: